apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: osnp3oyzf-nodejs-gitops
  description: This is GitOps manifest for osnp3oyzf-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=osnp3oyzf-nodejs
    backstage.io/kubernetes-id: osnp3oyzf-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: osnp3oyzf-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:osnp3oyzf-nodejs
